title: 'England First XI'
subtitle: 'England 2 - 0 Scotland'
description: 'EURO 1996 Group A, 15th June 1996'
formation: '41212'
participants:
  -
    shortName: Seaman
    type: participant
    enabled: true
  -
    shortName: Neville
    type: participant
    enabled: true
  -
    shortName: Adams
    type: participant
    enabled: true
  -
    shortName: Southgate
    type: participant
    enabled: true
  -
    shortName: Pearce
    type: participant
    enabled: true
  -
    shortName: Ince
    type: participant
    enabled: true
  -
    shortName: McManaman
    type: participant
    enabled: true
  -
    shortName: Gascoigne
    type: participant
    enabled: true
  -
    shortName: Anderton
    type: participant
    enabled: true
  -
    shortName: Sheringham
    type: participant
    enabled: true
  -
    shortName: Shearer
    type: participant
    enabled: true
updated_by: 2ebde1b1-216e-429c-a8c3-f0ec2c607d9d
updated_at: 1624304966
blueprint: missing_names
home_team_badge:
  - 10367-1624304843.png
away_team_badge:
  - Scotland_national_football_team_logo_2014.svg-1624304860.png
