title: Quizzical
replicator:
  -
    text: 'What is the best original starter Pokemon (red/blue)?'
    array:
      A: Charmander
      B: Bulbasaur
      C: Squirtle
    correct_answer: A
    type: question_and_answer
    enabled: true
  -
    text: 'Who Lives in Paris?'
    array:
      A: Emily
      B: Norbert
      C: 'Kristen Stewart'
    correct_answer: A
    type: question_and_answer
    enabled: true
  -
    text: 'Which food does Mo like?'
    array:
      A: KFC
      B: Nandos
      C: 'Burger King'
    correct_answer: C
    type: question_and_answer
    enabled: true
  -
    text: 'Is Elliot Welsh?'
    array:
      A: 'Yes'
      B: 'Yes'
      C: 'Yes'
    correct_answer: A
    type: question_and_answer
    enabled: true
  -
    text: 'Is Myke secretly Swedish Superstar Robyn?'
    array:
      A: 'Yes'
      B: Probably
      C: 'Hope so'
    correct_answer: A
    type: question_and_answer
    enabled: true
  -
    text: 'Henry the Eighth introduced which tax in England in 1535?'
    array:
      A: 'Window Tax'
      B: 'Monday Tax'
      C: 'Beard Tax'
    correct_answer: C
    type: question_and_answer
    enabled: true
updated_by: 2ebde1b1-216e-429c-a8c3-f0ec2c607d9d
updated_at: 1623409231
blueprint: quiz
