title: 'George Michael Quiz'
questions:
  -
    question: 'What band was GM in?'
    answers:
      A: Wham!
      B: 'Duran Duran'
      C: Busted
    type: new_set
    enabled: true
  -
    question: 'How old was GM when he wrote Careless Whisper'
    answers:
      A: '16'
      B: '18'
      C: '21'
    type: new_set
    enabled: true
updated_by: d105ca8c-d4f9-4688-a49d-16cbc04dd1cb
updated_at: 1621505497
blueprint: funquiz
